[theme]
primaryColor = "#2B59FF"
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
headless = true

[browser]
gatherUsageStats = false
