[theme]
primaryColor = "#18181B"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#09090B"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
